version: '3'
services:
  event-delivery-app:
    build:
      context: .
    ports:
      - "9410:9410" 
    depends_on:
      - redis
    environment:
     - REDIS_ADDR=redis:6379

  redis:
    image: redis:latest
    ports:
      - "6379:6379"