name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'

    - name: Build Docker image
      run: docker-compose build

    - name: Start Docker services
      run: docker-compose up -d

    - name: Wait for services to start
      run: sleep 10

    - name: Run Go tests
      run: docker-compose exec event-delivery-app go test ./...

    - name: Stop Docker services
      run: docker-compose down
